---
- name: making cache
  yum:
    update_cache: yes

- name: updating packages
  yum:
    name: '*'
    state: latest

- name: installing apache
  yum:
    name: httpd
    state: present

- name: starting and enabling httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: ensuring that /var/www/html/style directory exists
  file:
    path: /var/www/html/style
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: copying graphical files
  copy:
    src: "{{ item }}"
    dest: /var/www/html/style
    owner: root
    group: root
    mode: '0644'
  with_fileglob:
    - /home/ansible/project/roles/web1/graphical/*

- name: copying html files
  copy:
    src: "{{ item }}"
    dest: /var/www/html
    owner: root
    group: root
  with_fileglob:
    - /home/ansible/project/roles/web1/html/*

- name: restarting httpd
  service:
    name: httpd
    state: restarted