- name: Generate Docker Swarm join token on leader node
  command: docker swarm join-token -q worker
  register: swarm_join_token
  become: yes
  when: inventory_hostname == 'dock1'

- name: Store join token for workers
  set_fact:
    swarm_join_token: "{{ swarm_join_token.stdout }}"
  when: inventory_hostname == 'dock1'

- name: Save join token to a file on leader node
  copy:
    content: "{{ swarm_join_token }}"
    dest: "/tmp/docker_swarm_join_token.txt"
  when: inventory_hostname == 'dock1'

- name: Initialize Docker Swarm on the leader node
  docker_swarm:
    state: present
    role: manager
    advertise_addr: "{{ ansible_host }}"
  become: yes
  when: inventory_hostname == 'dock1'

- name: Fetch join token file from leader to worker nodes
  fetch:
    src: "/tmp/docker_swarm_join_token.txt"
    dest: "/tmp/"
  when: inventory_hostname in ['prdx-dworker201.ziyotek2.local', 'prdx-dworker202.ziyotek2.local']

- name: Join worker nodes to the Docker Swarm
  docker_swarm:
    state: present
    role: worker
    join_token: "{{ hostvars['dock1']['swarm_join_token'] }}"
    manager_ip: "prdx-dprimary201.ziyotek2.local"
  become: yes
  when: inventory_hostname in ['prdx-dworker201.ziyotek2.local', 'prdx-dworker202.ziyotek2.local']
