---
- name: making cache
  yum:
    update_cache: yes

- name: updating packages
  yum:
    name: '*'
    state: latest

- name: installing epel-release
  yum:
    name: epel-release
    state: present

- name: installing bind
  yum:
    name: bind
    state: present

- name: configuring named.conf
  template:
    src: namedconf.j2
    dest: /etc/named.conf
    backup: yes

- name: 