## updating all packages

- name: making cache
  yum:
    update_cache: yes

- name: updating packages
  yum:
    name: '*'
    state: latest

## configuring DNS

- name: getting uuid of network
  command: nmcli -g uuid con show
  register: uuid_result

- name: configuring network
  template:
    src: interface.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-ens192
    backup: yes

- name: restarting network
  service:
    name: network
    state: restarted

## configuring NTP

- name: ensure that chrony installed
  yum:
    name: chrony
    state: present

- name: start and enable chronyd
  service:
    name: chronyd
    state: started
    enabled: yes

- name: configuring chrony
  template:
    src: chronyconf.j2
    dest: /etc/chrony.conf
    backup: yes

- name: restarting chronyd
  service:
    name: chronyd
    state: restarted

## configuring FTP

- name: installing ftp
  yum:
    name: ftp
    state: present

## configuring NFS

- name: installing nfs
  yum:
    name: nfs-utils
    state: present

- name: starting and enabling services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - rpcbind
    - nfs-server
    - nfs-lock
    - nfs-idmap

- name: ensure that /clientshare exists
  file:
    path: /clientshare
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: temporary mounting nfs to /clientshare
  shell: mount -t nfs nfs:/var/nfs/shared /clientshare

- name: modifying /etc/fstab
  lineinfile:
    dest: /etc/fstab
    state: present
    regexp: '^nfs'
    line: 'nfs:/var/nfs/shared     /clientshare        nfs     rw,sync,hard,intr      0 0'

- name: updating permanent mounting
  shell: mount -a

## configuring LDAP

