## playbook for client side of the servers

- name: making cache
  yum:
    update_cache: yes

- name: updating packages
  yum:
    name: '*'
    state: latest

## configuring DNS

- name: getting uuid of network
  command: nmcli -g uuid con show
  register: uuid_result

- name: configuring network and DNS
  template:
    src: interface.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-ens192
    backup: yes

- name: restarting network
  service:
    name: network
    state: restarted

## configuring NTP

- name: ensure that chrony installed
  yum:
    name: chrony
    state: present

- name: start and enable chronyd
  service:
    name: chronyd
    state: started
    enabled: yes

- name: configuring chrony
  template:
    src: chronyconf.j2
    dest: /etc/chrony.conf
    backup: yes

- name: restarting chronyd
  service:
    name: chronyd
    state: restarted

## configuring FTP

- name: installing ftp
  yum:
    name: ftp
    state: present

## configuring LDAP

- name: installing necessary packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - openldap-clients
    - nss-pam-ldapd
    - wget
    - authconfig

- name: ensure that certs directory exists
  file:
    path: /etc/openldap/cacerts
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: getting CA.crt from LDAP server
  get_url:
    url: http://prdx-ldap201.ziyotek2.local/CA.crt
    dest: /etc/openldap/cacerts/CA.crt
    owner: root
    group: root
    mode: '0644'

- name: configuring authconfig for ldap recognition
  shell: authconfig --enableldap --enableldapauth --ldapserver=ldap://prdx-ldap201.ziyotek2.local/ --ldapbasedn="dc=ziyotek2,dc=local" --enableldaptls --enableshadow --enablelocauthorize --enablemkhomedir --update

## configuring Nagios

- name: installing epel-release
  yum:
    name: epel-release
    state: present

- name: installing nagios-plugins and nrpe
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - nrpe
    - nagios-plugins-all

- name: starting and enabling nrpe
  service:
    name: nrpe
    state: started
    enabled: yes

- name: configuring nrpe.cfg
  template:
    src: nrpecfg.j2
    dest: /etc/nagios/nrpe.cfg
    backup: yes

- name: restarting nrpe service
  service:
    name: nrpe
    state: restarted